# This is a basic workflow to help you get started with Actions

name: DEX Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the alpha branch
on:
  push:
    branches: [alpha]
  pull_request:
    branches: [alpha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Checkout serum-dex
        uses: actions/checkout@v2
        with:
          repository: serum-community/serum-dex
          path: serum-dex

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1

      - name: Install Cargo
        uses: actions-rs/cargo@v1.0.1

      # Runs a single command using the runners shell
      - name: Dex setup
        run: |
          curl -sSf https://raw.githubusercontent.com/solana-labs/solana/v1.3.9/install/solana-install-init.sh | sh -s - v1.3.9
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new -o ~/.config/solana/id.json --no-passphrase --silent
          solana address
          solana config get

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
